---
driver:
  name: docker
  binary: docker
  socket: <%= ENV.fetch('DOCKER_HOST', 'unix:///var/run/docker.sock') %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    driver_config:
      image: "ubuntu:14.04"

suites:
  - name: mesosphere_master
    run_list:
      - recipe[mesos::master]
    attributes:
      mesos:
        type: mesosphere
        mesosphere:
          with_zookeeper: true
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
  - name: mesosphere_slave
    run_list:
      # master recipe is only for asserting mesos-slave healthy startup.
      - recipe[mesos::master]
      - recipe[mesos::slave]
    attributes:
      mesos:
        type: mesosphere
        mesosphere:
          with_zookeeper: true
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        slave:
          master: 'zk://localhost:2181/mesos'
        # these keys below are only for master configurations.
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
  - name: source_master
    driver_config:
      # zookeeper is only for asserting mesos-master healthy startup.
      provision_command: "apt-get update && apt-get install -y zookeeper zookeeperd zookeeper-bin"
    run_list:
      - recipe[mesos::master]
    attributes:
      mesos:
        type: source
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
  - name: source_slave
    driver_config:
      # zookeeper is only for asserting mesos-master healthy startup.
      provision_command: "apt-get update && apt-get install -y zookeeper zookeeperd zookeeper-bin"
    run_list:
      # master recipe is only for asserting mesos-slave healthy startup.
      - recipe[mesos::master]
      - recipe[mesos::slave]
    attributes:
      mesos:
        type: source
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        slave:
          master: 'zk://localhost:2181/mesos'
        # these keys below are only for master configurations.
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
